//! THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
//! DO NOT EDIT THIS FILE MANUALLY


// START: UTOIPA DOCS
#[derive(utoipa::OpenApi)]
#[openapi(
    // FIX: No handler exists, so remove this path to prevent build error
    components(schemas()),
    tags((
        name = "drivepng", description = "drivepng endpoints"
    ))
)]
pub struct DrivepngApiDoc;
// END: UTOIPA DOCS

// START: API ROUTES
use axum::{routing::{get, post, put, delete, patch, head, options}, Router};
use crate::routes::ChatState;
use std::sync::Arc;

pub fn create_routes() -> Router<Arc<ChatState>> {
    Router::new()
        // FIX: No handler exists, so comment out or remove this route to prevent build error
}

// END: API ROUTES
