//! THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
//! DO NOT EDIT THIS FILE MANUALLY

pub mod drivepng;
pub mod drivepng_handler;

use axum::Router;
use std::sync::Arc;
use crate::routes::ChatState;

pub fn register_routes(mut router: Router<Arc<ChatState>>) -> Router<Arc<ChatState>> {
    router = drivepng::register_routes(router);
    router = drivepng_handler::register_routes(router);
    router
}
