//! THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
//! DO NOT EDIT THIS FILE MANUALLY

pub mod drivepng_handler;

#[utoipa::path(get, path = "/drivepng/drivepng_handler", tag = "drivepng", responses((status = 200, description = "drivepng handler", body = String), (status = 500, description = "Internal Server Error")))]
pub fn DRIVEPNG_HANDLER_UTOIPA() {}

use crate::routes::api::drivepng::drivepng_handler;

use axum::{routing::{get, post, put, delete, patch, head, options}, Router};
use crate::routes::ChatState;
use std::sync::Arc;

pub fn create_routes() -> Router<Arc<ChatState>> {
    let router = Router::new();
    let router = router.route("/drivepng/drivepng_handler", get(drivepng_handler::drivepng_handler));
    router
}
