//! THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
//! DO NOT EDIT THIS FILE MANUALLY

pub mod complete_anime_handler;

#[utoipa::path(get, path = "/api/anime/complete_anime", tag = "test", responses((status = 200, description = "Success", body = String), (status = 500, description = "Internal Server Error")))]
pub fn COMPLETE_ANIME_HANDLER_UTOIPA() {}

use crate::routes::api::anime::complete_anime::complete_anime_handler::complete_anime_handler;

use axum::{routing::{get, post, put, delete, patch, head, options}, Router};
use crate::routes::ChatState;
use std::sync::Arc;

pub fn create_routes() -> Router<Arc<ChatState>> {
    let router = Router::new();
    let router = router.route("/", get(complete_anime_handler));
    router
}
