//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "ChatRoom"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: String,
    pub name: String,
    pub description: Option<String>,
    pub is_private: i32,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
    Description,
    #[sea_orm(column_name = "is_private")]
    IsPrivate,
    #[sea_orm(column_name = "created_at")]
    CreatedAt,
    #[sea_orm(column_name = "updated_at")]
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    ChatMessageRoom,
    ChatRoomMember,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::String(StringLen::N(255u32)).def(),
            Self::Name => ColumnType::String(StringLen::N(255u32)).def(),
            Self::Description => ColumnType::Text.def().null(),
            Self::IsPrivate => ColumnType::Integer.def(),
            Self::CreatedAt => ColumnType::Timestamp.def(),
            Self::UpdatedAt => ColumnType::Timestamp.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::ChatMessageRoom => Entity::has_many(super::chat_message_room::Entity).into(),
            Self::ChatRoomMember => Entity::has_many(super::chat_room_member::Entity).into(),
        }
    }
}

impl Related<super::chat_message_room::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatMessageRoom.def()
    }
}

impl Related<super::chat_room_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatRoomMember.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
