//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "Posts"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: String,
    pub user_id: String,
    pub author_id: String,
    pub content: String,
    pub image_url: Option<String>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    #[sea_orm(column_name = "userId")]
    UserId,
    #[sea_orm(column_name = "authorId")]
    AuthorId,
    Content,
    ImageUrl,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Comments,
    Likes,
    User2,
    User1,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::String(StringLen::N(255u32)).def(),
            Self::UserId => ColumnType::String(StringLen::N(255u32)).def(),
            Self::AuthorId => ColumnType::String(StringLen::N(255u32)).def(),
            Self::Content => ColumnType::Text.def(),
            Self::ImageUrl => ColumnType::Text.def().null(),
            Self::CreatedAt => ColumnType::Timestamp.def(),
            Self::UpdatedAt => ColumnType::Timestamp.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Comments => Entity::has_many(super::comments::Entity).into(),
            Self::Likes => Entity::has_many(super::likes::Entity).into(),
            Self::User2 => Entity::belongs_to(super::user::Entity)
                .from(Column::AuthorId)
                .to(super::user::Column::Id)
                .into(),
            Self::User1 => Entity::belongs_to(super::user::Entity)
                .from(Column::UserId)
                .to(super::user::Column::Id)
                .into(),
        }
    }
}

impl Related<super::comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comments.def()
    }
}

impl Related<super::likes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Likes.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::likes::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::likes::Relation::Posts.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
