//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "User"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: String,
    pub name: Option<String>,
    pub email: Option<String>,
    pub email_verified: Option<DateTimeUtc>,
    pub image: Option<String>,
    pub password: Option<String>,
    pub refresh_token: Option<String>,
    pub role: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
    Email,
    #[sea_orm(column_name = "emailVerified")]
    EmailVerified,
    Image,
    Password,
    #[sea_orm(column_name = "refreshToken")]
    RefreshToken,
    Role,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Account,
    ChatMessage,
    ChatMessageRoom,
    ChatRoomMember,
    EmailVerificationToken,
    Likes,
    PasswordResetToken,
    Replies,
    Session,
    UserRole,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::String(StringLen::N(255u32)).def(),
            Self::Name => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::Email => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::EmailVerified => ColumnType::Timestamp.def().null(),
            Self::Image => ColumnType::Text.def().null(),
            Self::Password => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::RefreshToken => ColumnType::Text.def().null(),
            Self::Role => ColumnType::String(StringLen::N(50u32)).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Account => Entity::has_many(super::account::Entity).into(),
            Self::ChatMessage => Entity::has_many(super::chat_message::Entity).into(),
            Self::ChatMessageRoom => Entity::has_many(super::chat_message_room::Entity).into(),
            Self::ChatRoomMember => Entity::has_many(super::chat_room_member::Entity).into(),
            Self::EmailVerificationToken => {
                Entity::has_many(super::email_verification_token::Entity).into()
            }
            Self::Likes => Entity::has_many(super::likes::Entity).into(),
            Self::PasswordResetToken => {
                Entity::has_many(super::password_reset_token::Entity).into()
            }
            Self::Replies => Entity::has_many(super::replies::Entity).into(),
            Self::Session => Entity::has_many(super::session::Entity).into(),
            Self::UserRole => Entity::has_many(super::user_role::Entity).into(),
        }
    }
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl Related<super::chat_message::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatMessage.def()
    }
}

impl Related<super::chat_message_room::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatMessageRoom.def()
    }
}

impl Related<super::chat_room_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatRoomMember.def()
    }
}

impl Related<super::email_verification_token::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EmailVerificationToken.def()
    }
}

impl Related<super::likes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Likes.def()
    }
}

impl Related<super::password_reset_token::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PasswordResetToken.def()
    }
}

impl Related<super::replies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Replies.def()
    }
}

impl Related<super::session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Session.def()
    }
}

impl Related<super::user_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRole.def()
    }
}

impl Related<super::posts::Entity> for Entity {
    fn to() -> RelationDef {
        super::likes::Relation::Posts.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::likes::Relation::User.def().rev())
    }
}

impl Related<super::role::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_role::Relation::Role.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_role::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
