/// THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
/// DO NOT EDIT THIS FILE MANUALLY

pub mod complete_anime;
pub mod detail;
pub mod ongoing_anime;
pub mod search;

/// Register routes for this directory
use axum::Router;
use std::sync::Arc;
use crate::routes::AppState;
pub fn register_routes(router: Router<Arc<AppState>>) -> Router<Arc<AppState>> {
  complete_anime::register_routes(detail::register_routes(ongoing_anime::register_routes(search::register_routes(router))))
}
