/// THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
/// DO NOT EDIT THIS FILE MANUALLY

pub mod complete_anime;
pub mod detail;
pub mod filter;
pub mod genre;
pub mod genre_list;
pub mod index;
pub mod latest;
pub mod ongoing_anime;
pub mod search;

/// Register routes for this directory
use axum::Router;
use std::sync::Arc;
use crate::routes::AppState;
pub fn register_routes(router: Router<Arc<AppState>>) -> Router<Arc<AppState>> {
  complete_anime::register_routes(detail::register_routes(filter::register_routes(genre::register_routes(genre_list::register_routes(crate::routes::api::anime2::index::register_routes(latest::register_routes(ongoing_anime::register_routes(search::register_routes(router)))))))))
}
