//! THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
//! DO NOT EDIT THIS FILE MANUALLY

pub mod full_episode_handler;

#[utoipa::path(get, path = "/anime/full/full_episode_handler", tag = "full", responses((status = 200, description = "full episode handler", body = String), (status = 500, description = "Internal Server Error")))]
pub fn FULL_EPISODE_HANDLER_UTOIPA() {}

use crate::routes::api::anime::full::full_episode_handler;

use axum::{routing::{get, post, put, delete, patch, head, options}, Router};
use crate::routes::ChatState;
use std::sync::Arc;

pub fn create_routes() -> Router<Arc<ChatState>> {
    let router = Router::new();
    let router = router.route("/anime/full/full_episode_handler", get(full_episode_handler::full_episode_handler));
    router
}
