//! THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
//! DO NOT EDIT THIS FILE MANUALLY

pub mod uploader_handler;

#[utoipa::path(get, path = "/uploader/uploader_handler", tag = "uploader", responses((status = 200, description = "uploader handler", body = String), (status = 500, description = "Internal Server Error")))]
pub fn UPLOADER_HANDLER_UTOIPA() {}

use crate::routes::api::uploader::uploader_handler;

use axum::{routing::{get, post, put, delete, patch, head, options}, Router};
use crate::routes::ChatState;
use std::sync::Arc;

pub fn create_routes() -> Router<Arc<ChatState>> {
    let router = Router::new();
    let router = router.route("/uploader/uploader_handler", get(uploader_handler::uploader_handler));
    router
}
