/// THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
/// DO NOT EDIT THIS FILE MANUALLY

pub mod chapter;
pub mod detail;
pub mod genre;
pub mod genre_list;
pub mod manga;
pub mod manhua;
pub mod manhwa;
pub mod popular;
pub mod search;

/// Register routes for this directory
use axum::Router;
use std::sync::Arc;
use crate::routes::AppState;

pub fn register_routes(router: Router<Arc<AppState>>) -> Router<Arc<AppState>> {
    chapter::register_routes(detail::register_routes(genre::register_routes(genre_list::register_routes(manga::register_routes(manhua::register_routes(manhwa::register_routes(popular::register_routes(search::register_routes(router)))))))))
}
