//! THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
//! DO NOT EDIT THIS FILE MANUALLY

pub mod chapter;
pub mod detail;
pub mod manga;
pub mod manhua;
pub mod manhwa;
pub mod search;

use axum::Router;
use std::sync::Arc;
use crate::routes::ChatState;

pub fn register_routes(mut router: Router<Arc<ChatState>>) -> Router<Arc<ChatState>> {
    router = chapter::register_routes(router);
    router = detail::register_routes(router);
    router = manga::register_routes(router);
    router = manhua::register_routes(router);
    router = manhwa::register_routes(router);
    router = search::register_routes(router);
    router
}
