/// THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
/// DO NOT EDIT THIS FILE MANUALLY

pub mod chapter;
pub mod detail;
pub mod function;
pub mod manga;
pub mod manga;
pub mod manhua;
pub mod manhua;
pub mod manhwa;
pub mod manhwa;
pub mod search;

/// Register routes for this directory
use axum::Router;
use std::sync::Arc;
use crate::routes::AppState;

pub fn register_routes(router: Router<Arc<AppState>>) -> Router<Arc<AppState>> {
  chapter::register_routes(detail::register_routes(function::register_routes(manga::register_routes(manga::register_routes(manhua::register_routes(manhua::register_routes(manhwa::register_routes(manhwa::register_routes(search::register_routes(router))))))))))
}
