//! THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
//! DO NOT EDIT THIS FILE MANUALLY

pub mod detail_handler;

#[utoipa::path(get, path = "api/anime2/detail", tag = "test", responses((status = 200, description = "Success", body = String), (status = 500, description = "Internal Server Error")))]
pub fn DETAIL_HANDLER_UTOIPA() {}

use crate::routes::api::anime2::detail::detail_handler::detail_handler;

use axum::{routing::{get, post, put, delete, patch, head, options}, Router};
use crate::routes::ChatState;
use std::sync::Arc;

pub fn create_routes() -> Router<Arc<ChatState>> {
    let router = Router::new();
    let router = router.route("/api/anime2/detail", get(detail_handler));
    router
}
