//! THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
//! DO NOT EDIT THIS FILE MANUALLY

pub mod search_handler;

#[utoipa::path(get, path = "/anime2/search/search_handler", tag = "search", responses((status = 200, description = "search handler", body = String), (status = 500, description = "Internal Server Error")))]
pub fn SEARCH_HANDLER_UTOIPA() {}

use crate::routes::api::anime2::search::search_handler;

use axum::{routing::{get, post, put, delete, patch, head, options}, Router};
use crate::routes::ChatState;
use std::sync::Arc;

pub fn create_routes() -> Router<Arc<ChatState>> {
    let router = Router::new();
    let router = router.route("/anime2/search/search_handler", get(search_handler::search_handler));
    router
}
