/// THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
/// DO NOT EDIT THIS FILE MANUALLY

pub mod db;
pub mod messages;
pub mod models;
pub mod rooms;

/// Register routes for this directory
use axum::Router;
use std::sync::Arc;
use crate::routes::AppState;
pub fn register_routes(router: Router<Arc<AppState>>) -> Router<Arc<AppState>> {
  db::register_routes(messages::register_routes(models::register_routes(rooms::register_routes(router))))
}
