//! THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
//! DO NOT EDIT THIS FILE MANUALLY

pub mod chat_handler;

#[utoipa::path(get, path = "/chat/chat_handler", tag = "chat", responses((status = 200, description = "chat handler", body = String), (status = 500, description = "Internal Server Error")))]
pub fn CHAT_HANDLER_UTOIPA() {}

use crate::routes::api::chat::chat_handler;

use axum::{routing::{get, post, put, delete, patch, head, options}, Router};
use crate::routes::ChatState;
use std::sync::Arc;

pub fn create_routes() -> Router<Arc<ChatState>> {
    let router = Router::new();
    let router = router.route("/chat/chat_handler", get(chat_handler::chat_handler));
    router
}
