//! THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
//! DO NOT EDIT THIS FILE MANUALLY

// --- METADATA UNTUK BUILD.RS ---
const ENDPOINT_METHOD: &str = "GET";
const ENDPOINT_PATH: &str = "/api/komik/manga/{slug}";
const ENDPOINT_DESCRIPTION: &str = "Get details for a manga.";
const ENDPOINT_TAG: &str = "komik";
const SUCCESS_RESPONSE_BODY: &str = "MangaResponse";
const SLUG_DESCRIPTION: &str = "The slug of the manga.";
// --- AKHIR METADATA ---

use axum::{
    extract::Path,
    response::{IntoResponse, Response},
    Json,
};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Serialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct MangaData {
    pub message: String,
    pub slug: String,
}

#[derive(Serialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct MangaResponse {
    pub status: &'static str,
    pub data: MangaData,
}

/// Get details for a manga
#[utoipa::path(
    get,
    path = "/api/komik/manga/{slug}",
    tag = "komik",
    responses(
        (status = 200, description = "Success", body = MangaResponse),
        (status = 500, description = "Internal Server Error")
    ),
    params(
        ("slug" = String, Path, description = SLUG_DESCRIPTION)
    )
)]
pub fn MANGA_HANDLER_UTOIPA() {}

pub async fn manga_handler(Path(slug): Path<String>) -> Response {
    let response_data = MangaData {
        message: format!("Data for komik manga: {}", slug),
        slug: slug.clone(),
    };

    let response = MangaResponse {
        status: "Ok",
        data: response_data,
    };

    Json(response).into_response()
}


pub fn register_routes(router: Router<Arc<ChatState>>) -> Router<Arc<ChatState>> {
    router.route(ENDPOINT_PATH, axum::routing::GET(manga_handler))
}