services:
  elysia-api:
    image: ghcr.io/mytheclipse/ultimate-asepharyana.tech/elysia-api:sha-b769742
    restart: always
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      app-shared-net:
        aliases:
          - elysia-api
    environment:
      - DATABASE_URL=mysql://asephs:hunterz@mysql:3306/sosmed
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=273742
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=mytheclipse
      - MINIO_BUCKET_NAME=api

networks:
  app-shared-net:
    name: app-shared-net
    external: true
