services:
  elysia-api:
    image: ghcr.io/mytheclipse/ultimate-asepharyana.tech/elysia-api:sha-b769742
    restart: always
    networks: [app-shared-net]
    environment:
      - DATABASE_URL=mysql://asephs:hunterz@mysql:3306/sosmed
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=273742
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=mytheclipse
      - MINIO_BUCKET_NAME=api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elysia.rule=Host(`elysia.asepharyana.tech`)"
      - "traefik.docker.allowNonRunningContainers=true"
      - "traefik.http.routers.elysia.entrypoints=websecure"
      - "traefik.http.routers.elysia.tls=true"
      - "traefik.http.routers.elysia.middlewares=elysia-sablier,secure-headers@file,compress@file,retry@file,rate-limit@file,buffer@file"
      - "traefik.http.services.elysia.loadbalancer.server.port=4092"
      - "traefik.http.middlewares.elysia-sablier.plugin.sablier.sablierUrl=http://sablier:10000"
      - "traefik.http.middlewares.elysia-sablier.plugin.sablier.sessionDuration=5m"
      - "traefik.http.middlewares.elysia-sablier.plugin.sablier.names=elysia-api"
      - "traefik.http.middlewares.elysia-sablier.plugin.sablier.blocking.timeout=30s"

networks:
  app-shared-net:
    name: app-shared-net
    external: true
