services:
  leptos-web:
    image: ghcr.io/mytheclipse/ultimate-asepharyana.tech/leptos-web:sha-b769742
    restart: always
    networks: [app-shared-net]
    environment:
      - VITE_RUST_API=https://rust.asepharyana.tech
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leptos.rule=Host(`leptos.asepharyana.tech`)"
      - "traefik.http.routers.leptos.entrypoints=websecure"
      - "traefik.http.routers.leptos.tls=true"
      - "traefik.http.services.leptos.loadbalancer.server.port=80"
networks:
  app-shared-net:
    name: app-shared-net
    external: true
