services:
  leptos-web:
    image: ghcr.io/mytheclipse/ultimate-asepharyana.tech/leptos-web:sha-b769742
    restart: always
    networks: [app-shared-net]
    environment:
      - VITE_RUST_API=https://rust.asepharyana.tech
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leptos.rule=Host(`leptos.asepharyana.tech`)"
      - "traefik.http.routers.leptos.entrypoints=websecure"
      - "traefik.http.routers.leptos.tls=true"
      - "traefik.http.routers.leptos.middlewares=leptos-sablier,secure-headers@file,compress@file,retry@file,rate-limit@file,buffer@file"
      - "traefik.http.services.leptos.loadbalancer.server.port=80"
      - "traefik.http.middlewares.leptos-sablier.plugin.sablier.sablierUrl=http://sablier:10000"
      - "traefik.http.middlewares.leptos-sablier.plugin.sablier.sessionDuration=5m"
      - "traefik.http.middlewares.leptos-sablier.plugin.sablier.names=leptos-web"
      - "traefik.http.middlewares.leptos-sablier.plugin.sablier.dynamic.displayName=Leptos Web"
      - "traefik.http.middlewares.leptos-sablier.plugin.sablier.dynamic.theme=hacker-terminal"
networks:
  app-shared-net:
    name: app-shared-net
    external: true
