services:
  leptos-web:
    image: ghcr.io/mytheclipse/ultimate-asepharyana.tech/leptos-web:sha-1a49eeb
    restart: always
    networks: [app-shared-net]
    environment:
      - VITE_RUST_API=https://rust.asepharyana.tech
networks:
  app-shared-net:
    name: app-shared-net
    external: true
