services:
  picser:
    container_name: picser
    image: ghcr.io/mytheclipse/picser:sha-9f61efdd5c21545086586422095ec91a94a0ec6b
    restart: always
    networks:
      app-shared-net:
        aliases:
          - picser
    env_file:
      - .env.picser
networks:
  app-shared-net:
    name: app-shared-net
    external: true
