services:
  picser:
    image: ghcr.io/mytheclipse/picser:sha-e77b4e38c1b2c3289bcbbd01b4bf181aae82a322
    restart: always
    networks: [app-shared-net]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.picser.rule=Host(`picser.asepharyana.tech`)"
      - "traefik.http.routers.picser.entrypoints=websecure"
      - "traefik.http.routers.picser.tls=true"
      - "traefik.http.routers.picser.middlewares=picser-sablier,secure-headers@file,compress@file,retry@file,rate-limit@file,buffer@file"
      - "traefik.http.services.picser.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.picser-sablier.plugin.sablier.sablierUrl=http://sablier:10000"
      - "traefik.http.middlewares.picser-sablier.plugin.sablier.sessionDuration=5m"
      - "traefik.http.middlewares.picser-sablier.plugin.sablier.names=picser"
      - "traefik.http.middlewares.picser-sablier.plugin.sablier.blocking.timeout=30s"
    env_file:
      - .env.picser
networks:
  app-shared-net:
    name: app-shared-net
    external: true
