services:
  picser:
    image: ghcr.io/mytheclipse/picser:sha-e77b4e38c1b2c3289bcbbd01b4bf181aae82a322
    restart: always
    networks:
      app-shared-net:
        aliases:
          - picser
    env_file:
      - .env.picser
networks:
  app-shared-net:
    name: app-shared-net
    external: true
