services:
  rust-api:
    image: ghcr.io/mytheclipse/ultimate-asepharyana.cloud/rust-api:latest
    restart: always
    networks: [app-shared-net]
    environment:
      - DATABASE_URL=mysql://asephs:hunterz@mysql:3307/sosmed
      - REDIS_URL=redis://redis:6380
      - JWT_SECRET=273742
      - CHROME_REMOTE_WS=ws://browserless:3000

networks:
  app-shared-net:
    name: app-shared-net
    external: true
