services:
  rust-api:
    image: ghcr.io/mytheclipse/ultimate-asepharyana.tech/rust-api:sha-b769742
    restart: always
    networks: [app-shared-net]
    environment:
      - DATABASE_URL=mysql://asephs:hunterz@mysql:3306/sosmed
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=273742
      - EXTERNAL_BROWSERLESS_WS=${EXTERNAL_BROWSERLESS_WS}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rust.rule=Host(`rust.asepharyana.tech`)"
      - "traefik.docker.allowNonRunningContainers=true"
      - "traefik.http.routers.rust.entrypoints=websecure"
      - "traefik.http.routers.rust.tls=true"
      - "traefik.http.routers.rust.middlewares=rust-sablier,secure-headers@file,compress@file,retry@file,rate-limit@file,buffer@file"
      - "traefik.http.services.rust.loadbalancer.server.port=4091"
      - "traefik.http.middlewares.rust-sablier.plugin.sablier.sablierUrl=http://sablier:10000"
      - "traefik.http.middlewares.rust-sablier.plugin.sablier.sessionDuration=5m"
      - "traefik.http.middlewares.rust-sablier.plugin.sablier.names=rust-api"
      - "traefik.http.middlewares.rust-sablier.plugin.sablier.blocking.timeout=30s"
networks:
  app-shared-net:
    name: app-shared-net
    external: true
