services:
  mysql:
    image: 'mysql:8.4'
    restart: always
    networks:
      - app-shared-net
    environment:
      MYSQL_ROOT_PASSWORD: ${SHARED_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SHARED_MYSQL_DATABASE}
      MYSQL_USER: ${SHARED_MYSQL_USER}
      MYSQL_PASSWORD: ${SHARED_MYSQL_PASSWORD}
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-h'
        - 127.0.0.1
        - '-P'
        - '3306'
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - 'mysql_data:/var/lib/mysql'
      - '../config/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro'
  redis:
    image: 'redis:7.2-alpine'
    restart: always
    networks:
      - app-shared-net
    volumes:
      - 'redis_data:/data'
  minio:
    image: minio/minio
    restart: always
    networks:
      - app-shared-net
    environment:
      MINIO_ROOT_USER: ${SHARED_MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${SHARED_MINIO_ROOT_PASSWORD}
    command: 'server /data --console-address ":9001" --address ":9000"'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.minio.rule=Host(`minio.asepharyana.tech`)'
      - 'traefik.http.routers.minio.entrypoints=websecure'
      - 'traefik.http.routers.minio.tls=true'
      - 'traefik.http.routers.minio.middlewares=secure-headers@file,compress@file,retry@file,rate-limit@file,buffer@file'
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
      - "traefik.http.routers.minio-console.rule=Host(`minio-console.asepharyana.tech`)"
      - "traefik.http.routers.minio-console.entrypoints=websecure"
      - "traefik.http.routers.minio-console.tls=true"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.routers.minio-console.middlewares=secure-headers@file,compress@file,retry@file,rate-limit@file,buffer@file"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
    volumes:
      - 'minio_data:/data'
  sablier:
    image: 'sablierapp/sablier:1.11.2'
    restart: always
    networks:
      - app-shared-net
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    command:
      - start
      - '--provider.name=docker'
networks:
  app-shared-net:
    name: app-shared-net
    driver: bridge
volumes:
  mysql_data: null
  redis_data: null
  minio_data: null
