services:
  solidjs-web:
    image: ghcr.io/mytheclipse/ultimate-asepharyana.tech/solidjs-web:sha-b769742
    restart: always
    networks: [app-shared-net]
    labels:
    environment:
      - VITE_RUST_API=https://rust.asepharyana.tech
      - VITE_ELYSIA_API=https://elysia.asepharyana.tech
networks:
  app-shared-net:
    name: app-shared-net
    external: true
