services:
  solidjs-web:
    image: ghcr.io/mytheclipse/ultimate-asepharyana.cloud/solidjs-web:latest
    restart: always
    networks: [app-shared-net]
    environment:
      - VITE_RUST_API=https://rust.asepharyana.tech
      - VITE_ELYSIA_API=https://elysia.asepharyana.tech
    volumes:
      - ./nginx/solidjs.conf:/etc/nginx/http.d/default.conf:ro
networks:
  app-shared-net:
    name: app-shared-net
    external: true
