services:
  traefik:
    image: traefik:v2.11
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-shared-net
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=app-shared-net"
      - "--providers.docker.watch=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--accesslog=true"
      - "--entryPoints.websecure.address=:443"
    environment:
      - DOCKER_API_VERSION=1.41
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../traefik/dynamic:/etc/traefik/dynamic:ro
      - /root/asephstech.pem:/etc/traefik/certs/asephstech.pem:ro
      - /root/asephscloud.key:/etc/traefik/certs/asephscloud.key:ro
      - /data/coolify/proxy/certs/trace.pem:/etc/traefik/certs/trace.pem:ro
      - /data/coolify/proxy/certs/trace.key:/etc/traefik/certs/trace.key:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.asepharyana.tech`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"

networks:
  app-shared-net:
    name: app-shared-net
    external: true
