services:
  visuals:
    image: ghcr.io/mytheclipse/ultimate-asepharyana.tech/visuals:sha-ddfc146
    restart: always
    networks: [app-shared-net]
networks:
  app-shared-net:
    name: app-shared-net
    external: true
