//! THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
//! DO NOT EDIT THIS FILE MANUALLY

// --- METADATA UNTUK BUILD.RS ---
const ENDPOINT_METHOD: &str = "GET";
const ENDPOINT_PATH: &str = "/api/komik/chapter/{slug}";
const ENDPOINT_DESCRIPTION: &str = "Get details for a komik chapter.";
const ENDPOINT_TAG: &str = "komik";
const SUCCESS_RESPONSE_BODY: &str = "ChapterResponse";
const SLUG_DESCRIPTION: &str = "The slug of the komik chapter.";
// --- AKHIR METADATA ---

use axum::{
    extract::Path,
    response::{IntoResponse, Response},
    Json,
};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Serialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct ChapterData {
    pub message: String,
    pub slug: String,
}

#[derive(Serialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct ChapterResponse {
    pub status: &'static str,
    pub data: ChapterData,
}

/// Get details for a komik chapter
#[utoipa::path(
    get,
    path = "/api/komik/chapter/{slug}",
    tag = "komik",
    responses(
        (status = 200, description = "Success", body = ChapterResponse),
        (status = 500, description = "Internal Server Error")
    ),
    params(
        ("slug" = String, Path, description = SLUG_DESCRIPTION)
    )
)]
pub fn CHAPTER_HANDLER_UTOIPA() {}

pub async fn chapter_handler(Path(slug): Path<String>) -> Response {
    let response_data = ChapterData {
        message: format!("Data for komik chapter: {}", slug),
        slug: slug.clone(),
    };

    let response = ChapterResponse {
        status: "Ok",
        data: response_data,
    };

    Json(response).into_response()
}
