//! THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
//! DO NOT EDIT THIS FILE MANUALLY

use axum::Router;
use std::sync::Arc;
use crate::routes::AppState;

pub mod anime;
pub mod anime2;
pub mod auth;
pub mod compress;
pub mod drivepng;
pub mod komik;
pub mod proxy;
pub mod uploader;

use crate::routes::api::anime2::complete_anime::slug::CompleteAnimeItem;
use crate::routes::api::anime2::complete_anime::slug::ListResponse;
use crate::routes::api::anime2::complete_anime::slug::Pagination;
use crate::routes::api::anime2::detail::slug::AnimeDetailData;
use crate::routes::api::anime2::detail::slug::DetailResponse;
use crate::routes::api::anime2::detail::slug::DownloadItem;
use crate::routes::api::anime2::detail::slug::Genre;
use crate::routes::api::anime2::detail::slug::Link;
use crate::routes::api::anime2::detail::slug::Recommendation;
use crate::routes::api::anime2::index::Anime2Data;
use crate::routes::api::anime2::index::Anime2Response;
use crate::routes::api::anime2::index::CompleteAnimeItem as CompleteAnimeItem_1;
use crate::routes::api::anime2::index::OngoingAnimeItem;
use crate::routes::api::anime2::ongoing_anime::slug::OngoingAnimeItem as OngoingAnimeItem_1;
use crate::routes::api::anime2::ongoing_anime::slug::OngoingAnimeResponse;
use crate::routes::api::anime2::ongoing_anime::slug::Pagination as Pagination_1;
use crate::routes::api::anime2::search::AnimeItem;
use crate::routes::api::anime2::search::Pagination as Pagination_2;
use crate::routes::api::anime2::search::SearchQuery;
use crate::routes::api::anime2::search::SearchResponse;
use crate::routes::api::anime::complete_anime::slug::CompleteAnimeItem as CompleteAnimeItem_2;
use crate::routes::api::anime::complete_anime::slug::ListResponse as ListResponse_1;
use crate::routes::api::anime::complete_anime::slug::Pagination as Pagination_3;
use crate::routes::api::anime::detail::slug::AnimeDetailData as AnimeDetailData_1;
use crate::routes::api::anime::detail::slug::DetailResponse as DetailResponse_1;
use crate::routes::api::anime::detail::slug::EpisodeList;
use crate::routes::api::anime::detail::slug::Genre as Genre_1;
use crate::routes::api::anime::detail::slug::Recommendation as Recommendation_1;
use crate::routes::api::anime::full::slug::AnimeFullData;
use crate::routes::api::anime::full::slug::AnimeInfo;
use crate::routes::api::anime::full::slug::DownloadLink;
use crate::routes::api::anime::full::slug::EpisodeInfo;
use crate::routes::api::anime::full::slug::FullResponse;
use crate::routes::api::anime::index::AnimeData;
use crate::routes::api::anime::index::AnimeResponse;
use crate::routes::api::anime::index::CompleteAnimeItem as CompleteAnimeItem_3;
use crate::routes::api::anime::index::OngoingAnimeItem as OngoingAnimeItem_2;
use crate::routes::api::anime::ongoing_anime::slug::OngoingAnimeItem as OngoingAnimeItem_3;
use crate::routes::api::anime::ongoing_anime::slug::OngoingAnimeResponse as OngoingAnimeResponse_1;
use crate::routes::api::anime::ongoing_anime::slug::Pagination as Pagination_4;
use crate::routes::api::anime::search::AnimeItem as AnimeItem_1;
use crate::routes::api::anime::search::Pagination as Pagination_5;
use crate::routes::api::anime::search::SearchQuery as SearchQuery_1;
use crate::routes::api::anime::search::SearchResponse as SearchResponse_1;
use crate::routes::api::auth::change_password::ChangePasswordRequest;
use crate::routes::api::auth::change_password::ChangePasswordResponse;
use crate::routes::api::auth::delete_account::DeleteAccountRequest;
use crate::routes::api::auth::delete_account::DeleteAccountResponse;
use crate::routes::api::auth::forgot_password::ForgotPasswordRequest;
use crate::routes::api::auth::forgot_password::ForgotPasswordResponse;
use crate::routes::api::auth::login::LoginRequest;
use crate::routes::api::auth::logout::LogoutRequest;
use crate::routes::api::auth::logout::LogoutResponse;
use crate::routes::api::auth::profile::UpdateProfileRequest;
use crate::routes::api::auth::profile::UpdateProfileResponse;
use crate::routes::api::auth::refresh_token::RefreshRequest;
use crate::routes::api::auth::refresh_token::RefreshResponse;
use crate::routes::api::auth::register::RegisterRequest;
use crate::routes::api::auth::register::RegisterResponse;
use crate::routes::api::auth::reset_password::ResetPasswordRequest;
use crate::routes::api::auth::reset_password::ResetPasswordResponse;
use crate::routes::api::auth::verify::ResendVerificationRequest;
use crate::routes::api::auth::verify::VerifyQuery;
use crate::routes::api::auth::verify::VerifyResponse;
use crate::routes::api::compress::CompressQuery;
use crate::routes::api::compress::CompressResponse;
use crate::routes::api::drivepng::ListResponse as ListResponse_2;
use crate::routes::api::komik::chapter::ChapterData;
use crate::routes::api::komik::chapter::ChapterQuery;
use crate::routes::api::komik::chapter::ChapterResponse;
use crate::routes::api::komik::detail::Chapter;
use crate::routes::api::komik::detail::DetailData;
use crate::routes::api::komik::detail::DetailQuery;
use crate::routes::api::komik::detail::DetailResponse as DetailResponse_2;
use crate::routes::api::komik::detail::KomikDetailRequest;
use crate::routes::api::komik::manga::slug::MangaItem;
use crate::routes::api::komik::manga::slug::MangaResponse;
use crate::routes::api::komik::manga::slug::Pagination as Pagination_6;
use crate::routes::api::komik::manga::slug::QueryParams;
use crate::routes::api::komik::manhua::slug::ManhuaItem;
use crate::routes::api::komik::manhua::slug::ManhuaResponse;
use crate::routes::api::komik::manhua::slug::Pagination as Pagination_7;
use crate::routes::api::komik::manhua::slug::QueryParams as QueryParams_1;
use crate::routes::api::komik::manhwa::slug::ManhwaItem;
use crate::routes::api::komik::manhwa::slug::ManhwaResponse;
use crate::routes::api::komik::manhwa::slug::Pagination as Pagination_8;
use crate::routes::api::komik::manhwa::slug::QueryParams as QueryParams_2;
use crate::routes::api::komik::search::MangaItem as MangaItem_1;
use crate::routes::api::komik::search::Pagination as Pagination_9;
use crate::routes::api::komik::search::SearchQuery as SearchQuery_2;
use crate::routes::api::komik::search::SearchResponse as SearchResponse_2;
use crate::routes::api::proxy::croxy::ProxyParams;
use crate::routes::api::proxy::image_cache::ImageCacheBatchRequest;
use crate::routes::api::proxy::image_cache::ImageCacheBatchResponse;
use crate::routes::api::proxy::image_cache::ImageCacheRequest;
use crate::routes::api::proxy::image_cache::ImageCacheResponse;
use crate::routes::api::proxy::image_cache::ImageCacheResult;
use crate::routes::api::uploader::ListResponse as ListResponse_3;
#[derive(utoipa::OpenApi)]
#[openapi(
paths(
              crate::routes::api::proxy::croxy::fetch_with_proxy_only,
              crate::routes::api::proxy::image_cache::image_cache,
              crate::routes::api::komik::manhwa::slug::list,
              crate::routes::api::komik::manhua::slug::list,
              crate::routes::api::komik::manga::slug::list,
              crate::routes::api::komik::chapter::chapter,
              crate::routes::api::komik::detail::detail,
              crate::routes::api::komik::search::search,
              crate::routes::api::auth::change_password::change_password,
              crate::routes::api::auth::delete_account::delete_account,
              crate::routes::api::auth::forgot_password::forgot_password,
              crate::routes::api::auth::login::login,
              crate::routes::api::auth::logout::logout,
              crate::routes::api::auth::me::get_me,
              crate::routes::api::auth::profile::update_profile,
              crate::routes::api::auth::refresh_token::refresh,
              crate::routes::api::auth::register::register,
              crate::routes::api::auth::reset_password::reset_password,
              crate::routes::api::auth::verify::verify,
              crate::routes::api::anime2::ongoing_anime::slug::slug,
              crate::routes::api::anime2::detail::slug::slug,
              crate::routes::api::anime2::complete_anime::slug::slug,
              crate::routes::api::anime2::index::anime2,
              crate::routes::api::anime2::search::search,
              crate::routes::api::anime::ongoing_anime::slug::slug,
              crate::routes::api::anime::full::slug::slug,
              crate::routes::api::anime::detail::slug::slug,
              crate::routes::api::anime::complete_anime::slug::slug,
              crate::routes::api::anime::index::anime,
              crate::routes::api::anime::search::search,
              crate::routes::api::compress::compress,
              crate::routes::api::drivepng::drivepng,
              crate::routes::api::uploader::uploader
        ),
components(
            schemas(
                  CompleteAnimeItem,
                  ListResponse,
                  Pagination,
                  AnimeDetailData,
                  DetailResponse,
                  DownloadItem,
                  Genre,
                  Link,
                  Recommendation,
                  Anime2Data,
                  Anime2Response,
                  CompleteAnimeItem_1,
                  OngoingAnimeItem,
                  OngoingAnimeItem_1,
                  OngoingAnimeResponse,
                  Pagination_1,
                  AnimeItem,
                  Pagination_2,
                  SearchQuery,
                  SearchResponse,
                  CompleteAnimeItem_2,
                  ListResponse_1,
                  Pagination_3,
                  AnimeDetailData_1,
                  DetailResponse_1,
                  EpisodeList,
                  Genre_1,
                  Recommendation_1,
                  AnimeFullData,
                  AnimeInfo,
                  DownloadLink,
                  EpisodeInfo,
                  FullResponse,
                  AnimeData,
                  AnimeResponse,
                  CompleteAnimeItem_3,
                  OngoingAnimeItem_2,
                  OngoingAnimeItem_3,
                  OngoingAnimeResponse_1,
                  Pagination_4,
                  AnimeItem_1,
                  Pagination_5,
                  SearchQuery_1,
                  SearchResponse_1,
                  ChangePasswordRequest,
                  ChangePasswordResponse,
                  DeleteAccountRequest,
                  DeleteAccountResponse,
                  ForgotPasswordRequest,
                  ForgotPasswordResponse,
                  LoginRequest,
                  LogoutRequest,
                  LogoutResponse,
                  UpdateProfileRequest,
                  UpdateProfileResponse,
                  RefreshRequest,
                  RefreshResponse,
                  RegisterRequest,
                  RegisterResponse,
                  ResetPasswordRequest,
                  ResetPasswordResponse,
                  ResendVerificationRequest,
                  VerifyQuery,
                  VerifyResponse,
                  CompressQuery,
                  CompressResponse,
                  ListResponse_2,
                  ChapterData,
                  ChapterQuery,
                  ChapterResponse,
                  Chapter,
                  DetailData,
                  DetailQuery,
                  DetailResponse_2,
                  KomikDetailRequest,
                  MangaItem,
                  MangaResponse,
                  Pagination_6,
                  QueryParams,
                  ManhuaItem,
                  ManhuaResponse,
                  Pagination_7,
                  QueryParams_1,
                  ManhwaItem,
                  ManhwaResponse,
                  Pagination_8,
                  QueryParams_2,
                  MangaItem_1,
                  Pagination_9,
                  SearchQuery_2,
                  SearchResponse_2,
                  ProxyParams,
                  ImageCacheBatchRequest,
                  ImageCacheBatchResponse,
                  ImageCacheRequest,
                  ImageCacheResponse,
                  ImageCacheResult,
                  ListResponse_3
            )
        ),
modifiers(&SecurityAddon),
security((
            "bearer_auth" = []
        )),
servers(
            (url = "https://ws.asepharyana.tech", description = "Production Server"),
            (url = "http://localhost:4091", description = "Local Development")
        ),
info(
            title = "Freefire API",
            version = "0.0.1",
            description = "Free API for anime, manga, and more"
        ),
tags(
            (name = "api", description = "Main API"),
            (name = "auth", description = "Authentication endpoints")
        )
)]
#[allow(dead_code)]
pub struct ApiDoc;

struct SecurityAddon;

impl utoipa::Modify for SecurityAddon {
        fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
            use utoipa::openapi::security::*;
            if let Some(components) = openapi.components.as_mut() {
                components.add_security_scheme(
                    "bearer_auth",
                    SecurityScheme::Http(
                        HttpBuilder::new()
                            .scheme(HttpAuthScheme::Bearer)
                            .bearer_format("JWT")
                            .build()
                    ),
                )
            }
        }
    }

pub fn create_api_routes() -> Router<Arc<AppState>> {
    let mut router = Router::new();
    router = anime::register_routes(router);
    router = anime2::register_routes(router);
    router = auth::register_routes(router);
    router = compress::register_routes(router);
    router = drivepng::register_routes(router);
    router = komik::register_routes(router);
    router = proxy::register_routes(router);
    router = uploader::register_routes(router);
    router
}
