//! THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
//! DO NOT EDIT THIS FILE MANUALLY

use axum::Router;
use std::sync::Arc;
use crate::routes::AppState;

pub mod products;
pub mod test;

#[derive(utoipa::OpenApi)]
#[openapi(
paths(
              crate::routes::api::products::detail::product_id::product_id,
              crate::routes::api::test::hello::hello
          ),
components(
              schemas(

              )
          ),
tags(
              (name = "api", description = "Main API")
          )
)]
#[allow(dead_code)]
pub struct ApiDoc;

pub fn create_api_routes() -> Router<Arc<AppState>> {
    let mut router = Router::new();
    router = products::register_routes(router);
    router = test::register_routes(router);
    router
}
