//! THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
//! DO NOT EDIT THIS FILE MANUALLY

use axum::Router;
use std::sync::Arc;
use utoipa::OpenApi;
use crate::routes::AppState;

pub mod test;


#[derive(OpenApi)]
#[openapi(
    paths(
        crate::routes::api::test::helloworld::helloworld
    ),
    components(schemas()),
    tags((
        name = "api", description = "Main API"
    ))
)]
#[allow(dead_code)]
pub struct ApiDoc;

pub fn create_api_routes() -> Router<Arc<AppState>> {
    let mut router = Router::new();
    router = test::register_routes(router);
    router
}
