//! THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
//! DO NOT EDIT THIS FILE MANUALLY

// --- METADATA UNTUK BUILD.RS ---
const ENDPOINT_METHOD: &str = "GET";
const ENDPOINT_PATH: &str = "/api/komik/manhua/{slug}";
const ENDPOINT_DESCRIPTION: &str = "Get details for a manhua.";
const ENDPOINT_TAG: &str = "komik";
const SUCCESS_RESPONSE_BODY: &str = "ManhuaResponse";
const SLUG_DESCRIPTION: &str = "The slug of the manhua.";
// --- AKHIR METADATA ---

use axum::{
    extract::Path,
    response::{IntoResponse, Response},
    Json,
};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Serialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct ManhuaData {
    pub message: String,
    pub slug: String,
}

#[derive(Serialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct ManhuaResponse {
    pub status: &'static str,
    pub data: ManhuaData,
}

/// Get details for a manhua
#[utoipa::path(
    get,
    path = "/api/komik/manhua/{slug}",
    tag = "komik",
    responses(
        (status = 200, description = "Success", body = ManhuaResponse),
        (status = 500, description = "Internal Server Error")
    ),
    params(
        ("slug" = String, Path, description = SLUG_DESCRIPTION)
    )
)]
pub fn MANHUA_HANDLER_UTOIPA() {}

pub async fn manhua_handler(Path(slug): Path<String>) -> Response {
    let response_data = ManhuaData {
        message: format!("Data for komik manhua: {}", slug),
        slug: slug.clone(),
    };

    let response = ManhuaResponse {
        status: "Ok",
        data: response_data,
    };

    Json(response).into_response()
}


pub fn register_routes(router: Router<Arc<ChatState>>) -> Router<Arc<ChatState>> {
    router.route(ENDPOINT_PATH, axum::routing::GET(manhua_handler))
}