//! THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
//! DO NOT EDIT THIS FILE MANUALLY

pub mod manhua_handler;

#[utoipa::path(get, path = "/komik/manhua/manhua_handler", tag = "manhua", responses((status = 200, description = "manhua handler", body = String), (status = 500, description = "Internal Server Error")))]
pub fn MANHUA_HANDLER_UTOIPA() {}

use crate::routes::api::komik::manhua::manhua_handler;

use axum::{routing::{get, post, put, delete, patch, head, options}, Router};
use crate::routes::ChatState;
use std::sync::Arc;

pub fn create_routes() -> Router<Arc<ChatState>> {
    let router = Router::new();
    let router = router.route("/komik/manhua/manhua_handler", get(manhua_handler::manhua_handler));
    router
}
