//! THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
//! DO NOT EDIT THIS FILE MANUALLY

pub mod compress_service;
pub mod tests;

#[utoipa::path(get, path = "/api/compress", tag = "test", responses((status = 200, description = "Success", body = String), (status = 500, description = "Internal Server Error")))]
pub fn COMPRESS_SERVICE_UTOIPA() {}

use crate::routes::api::compress::compress_service::compress_service;

use axum::{routing::{get, post, put, delete, patch, head, options}, Router};
use crate::routes::ChatState;
use std::sync::Arc;

pub fn create_routes() -> Router<Arc<ChatState>> {
    let router = Router::new();
    let router = router.route("/", get(compress_service));
    router
}
