import { ChatMessage } from '@asepharyana/database';

export function validateChatMessage(message: any): { isValid: boolean; errors: string[]; validatedMessage?: ChatMessage } {
  const errors: string[] = [];

  if (!message || typeof message !== 'object') {
    errors.push('Message must be a valid object.');
  }

  if (!message.text || typeof message.text !== 'string' || message.text.trim() === '') {
    errors.push('Message text is required and must be a non-empty string.');
  }

  const validatedMessage: ChatMessage = {
    id: message.id || '', // Will be generated by uuid in controller
    userId: message.userId || `User${Math.floor(Math.random() * 1000)}`,
    text: message.text ? message.text.trim() : '',
    email: message.email || '',
    imageProfile: message.imageProfile || '',
    imageMessage: message.imageMessage || '',
    role: message.role || 'guest',
    timestamp: message.timestamp || new Date(),
  };

  return { isValid: errors.length === 0, errors, validatedMessage };
}
