//! THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
//! DO NOT EDIT THIS FILE MANUALLY

pub mod manhwa_handler;

#[utoipa::path(get, path = "/komik/manhwa/manhwa_handler", tag = "manhwa", responses((status = 200, description = "manhwa handler", body = String), (status = 500, description = "Internal Server Error")))]
pub fn MANHWA_HANDLER_UTOIPA() {}

use crate::routes::api::komik::manhwa::manhwa_handler;

use axum::{routing::{get, post, put, delete, patch, head, options}, Router};
use crate::routes::ChatState;
use std::sync::Arc;

pub fn create_routes() -> Router<Arc<ChatState>> {
    let router = Router::new();
    let router = router.route("/komik/manhwa/manhwa_handler", get(manhwa_handler::manhwa_handler));
    router
}
