use once_cell::sync::Lazy;
use regex::Regex;

pub static HANDLER_FN_REGEX: Lazy<Regex> =
    Lazy::new(|| Regex::new(r"pub async fn\s+([a-zA-Z0-9_]+)\s*\(").unwrap());

pub static ENDPOINT_METADATA_REGEX: Lazy<Regex> = Lazy::new(|| {
    Regex::new(
      r#"const\s+(ENDPOINT_METHOD|ENDPOINT_PATH|ENDPOINT_DESCRIPTION|ENDPOINT_TAG|OPERATION_ID|SUCCESS_RESPONSE_BODY):\s*&\s*str\s*=\s*"([^"]*)";"#
    ).unwrap()
});

pub static DYNAMIC_REGEX: Lazy<Regex> = Lazy::new(|| Regex::new(r"\[([^\]]+)\]").unwrap());

pub static API_ROUTE_REGEX: Lazy<Regex> = Lazy::new(|| {
    Regex::new(r"#\[api_route\(([\s\S]*?)\)\]").unwrap()
});

pub static UTOIPA_PATH_REGEX: Lazy<Regex> = Lazy::new(|| {
    Regex::new(r"#\[utoipa::path\(([\s\S]*?)\)\]").unwrap()
});

pub static HANDLER_WITH_PATH_REGEX: Lazy<Regex> = Lazy::new(|| {
    Regex::new(r"(?s)#\[utoipa::path\(([\s\S]*?)\)\]\s*(?:#\[.*?\]\s*)*pub async fn\s+([a-zA-Z0-9_]+)").unwrap()
});


pub const OPENAPI_HEADER: &str = r#"//! THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
//! DO NOT EDIT THIS FILE MANUALLY

use axum::Router;
use std::sync::Arc;
use crate::routes::AppState;
"#;

pub const SECURITY_ADDON_CODE: &str = r#"
    struct SecurityAddon;

    impl utoipa::Modify for SecurityAddon {
        fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
            use utoipa::openapi::security::*;
            if let Some(components) = openapi.components.as_mut() {
                components.add_security_scheme(
                    "bearer_auth",
                    SecurityScheme::Http(
                        HttpBuilder::new()
                            .scheme(HttpAuthScheme::Bearer)
                            .bearer_format("JWT")
                            .build()
                    ),
                )
            }
        }
    }
"#;

pub const OPENAPI_DOC_TEMPLATE: &str = r#"#[derive(utoipa::OpenApi)]
    #[openapi(
        paths(
{}
        ),
        components(
            schemas(
{}
            )
        ),
        modifiers(&SecurityAddon),
        security((
            "bearer_auth" = []
        )),
        servers(
            (url = "https://ws.asepharyana.tech", description = "Production Server"),
            (url = "http://localhost:4091", description = "Local Development")
        ),
        info(
            title = "Freefire API",
            version = "0.0.1",
            description = "Free API for anime, manga, and more"
        ),
        tags(
            (name = "auth", description = "Authentication endpoints")
        )
    )]
    #[allow(dead_code)]
    pub struct ApiDoc;
"#;
