/// THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
/// DO NOT EDIT THIS FILE MANUALLY

pub mod helloworld;

/// Register routes for this directory
use axum::Router;
use std::sync::Arc;
use crate::routes::AppState;
pub fn register_routes(router: Router<Arc<AppState>>) -> Router<Arc<AppState>> {
  helloworld::register_routes(router)
}
