/// THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
/// DO NOT EDIT THIS FILE MANUALLY
pub mod change_password;
pub mod delete_account;
pub mod forgot_password;
pub mod login;
pub mod logout;
pub mod me;
pub mod profile;
pub mod profile_image;
pub mod refresh_token;
pub mod register;
pub mod reset_password;
pub mod verify;

use crate::routes::AppState;
/// Register routes for this directory
use axum::Router;
use std::sync::Arc;

pub fn register_routes(router: Router<Arc<AppState>>) -> Router<Arc<AppState>> {
    change_password::register_routes(delete_account::register_routes(
        forgot_password::register_routes(login::register_routes(logout::register_routes(
            me::register_routes(profile::register_routes(profile_image::register_routes(
                refresh_token::register_routes(register::register_routes(
                    reset_password::register_routes(verify::register_routes(router)),
                )),
            ))),
        ))),
    ))
}
