/// THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
/// DO NOT EDIT THIS FILE MANUALLY

pub mod login;
pub mod logout;
pub mod register;
pub mod verify;

/// Register routes for this directory
use axum::Router;
use std::sync::Arc;
use crate::routes::AppState;
pub fn register_routes(router: Router<Arc<AppState>>) -> Router<Arc<AppState>> {
  login::register_routes(logout::register_routes(register::register_routes(verify::register_routes(router))))
}
