//! THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
//! DO NOT EDIT THIS FILE MANUALLY

pub mod ongoing;
pub mod ongoing_anime_handler;

use axum::Router;
use std::sync::Arc;
use crate::routes::ChatState;

pub fn register_routes(mut router: Router<Arc<ChatState>>) -> Router<Arc<ChatState>> {
    router = ongoing::register_routes(router);
    router = ongoing_anime_handler::register_routes(router);
    router
}
