/// THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
/// DO NOT EDIT THIS FILE MANUALLY

pub mod compress;
pub mod drivepng;
pub mod uploader;

/// Register routes for this directory
use axum::Router;
use std::sync::Arc;
use crate::routes::AppState;

pub fn register_routes(router: Router<Arc<AppState>>) -> Router<Arc<AppState>> {
    compress::register_routes(drivepng::register_routes(uploader::register_routes(router)))
}
