//! THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
//! DO NOT EDIT THIS FILE MANUALLY

pub mod detail_handler;

#[utoipa::path(get, path = "/anime/detail/detail_handler", tag = "detail", responses((status = 200, description = "detail handler", body = String), (status = 500, description = "Internal Server Error")))]
pub fn DETAIL_HANDLER_UTOIPA() {}

use crate::routes::api::anime::detail::detail_handler;

use axum::{routing::{get, post, put, delete, patch, head, options}, Router};
use crate::routes::ChatState;
use std::sync::Arc;

pub fn create_routes() -> Router<Arc<ChatState>> {
    let router = Router::new();
    let router = router.route("/anime/detail/detail_handler", get(detail_handler::detail_handler));
    router
}
