//! THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
//! DO NOT EDIT THIS FILE MANUALLY

// --- METADATA UNTUK BUILD.RS ---
const ENDPOINT_METHOD: &str = "GET";
const ENDPOINT_PATH: &str = "/api/komik/search/{slug}";
const ENDPOINT_DESCRIPTION: &str = "Search for komik.";
const ENDPOINT_TAG: &str = "komik";
const SUCCESS_RESPONSE_BODY: &str = "SearchResponse";
const SLUG_DESCRIPTION: &str = "The search query for komik.";
// --- AKHIR METADATA ---

use axum::{
    extract::Path,
    response::{IntoResponse, Response},
    Json,
};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Serialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct SearchData {
    pub message: String,
    pub slug: String,
}

#[derive(Serialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct SearchResponse {
    pub status: &'static str,
    pub data: SearchData,
}

/// Search for komik
#[utoipa::path(
    get,
    path = "/api/komik/search/{slug}",
    tag = "komik",
    responses(
        (status = 200, description = "Success", body = SearchResponse),
        (status = 500, description = "Internal Server Error")
    ),
    params(
        ("slug" = String, Path, description = SLUG_DESCRIPTION)
    )
)]
pub fn SEARCH_HANDLER_UTOIPA() {}

pub async fn search_handler(Path(slug): Path<String>) -> Response {
    let response_data = SearchData {
        message: format!("Search results for komik: {}", slug),
        slug: slug.clone(),
    };

    let response = SearchResponse {
        status: "Ok",
        data: response_data,
    };

    Json(response).into_response()
}


pub fn register_routes(router: Router<Arc<ChatState>>) -> Router<Arc<ChatState>> {
    router.route(ENDPOINT_PATH, axum::routing::GET(search_handler))
}