/// THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
/// DO NOT EDIT THIS FILE MANUALLY
pub mod croxy;
pub mod image_cache;

use crate::routes::AppState;
/// Register routes for this directory
use axum::Router;
use std::sync::Arc;

pub fn register_routes(router: Router<Arc<AppState>>) -> Router<Arc<AppState>> {
    croxy::register_routes(image_cache::register_routes(router))
}
