//! THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
//! DO NOT EDIT THIS FILE MANUALLY

// --- METADATA UNTUK BUILD.RS ---
const ENDPOINT_METHOD: &str = "GET";
const ENDPOINT_PATH: &str = "/api/proxy/{slug}";
const ENDPOINT_DESCRIPTION: &str = "A generic proxy endpoint.";
const ENDPOINT_TAG: &str = "proxy";
const SUCCESS_RESPONSE_BODY: &str = "ProxyResponse";
const SLUG_DESCRIPTION: &str = "The path to proxy.";
// --- AKHIR METADATA ---

use axum::{
    extract::Path,
    response::{IntoResponse, Response},
    Json,
};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Serialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct ProxyData {
    pub message: String,
    pub slug: String,
}

#[derive(Serialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct ProxyResponse {
    pub status: &'static str,
    pub data: ProxyData,
}

/// Generic proxy endpoint
#[utoipa::path(
    get,
    path = "/api/proxy/{slug}",
    tag = "proxy",
    responses(
        (status = 200, description = "Success", body = ProxyResponse),
        (status = 500, description = "Internal Server Error")
    ),
    params(
        ("slug" = String, Path, description = SLUG_DESCRIPTION)
    )
)]
pub fn PROXY_HANDLER_UTOIPA() {}

pub async fn proxy_handler(Path(slug): Path<String>) -> Response {
    let response_data = ProxyData {
        message: format!("Proxying request for: {}", slug),
        slug: slug.clone(),
    };

    let response = ProxyResponse {
        status: "Ok",
        data: response_data,
    };

    Json(response).into_response()
}
